### ISSUE TITLE
Adicionar configuração SSL para conexão com banco de dados

### ISSUE THREAD

**Issue by tiagos4ntos** [thiagocleite/ListaApp#1]
https://github.com/thiagocleite/ListaApp/blob/3a6f731e6e584ea0f3ba9831ab56023cb54cd3a6/backend/src/app.module.ts#L19

Adicionar o parâmetro `ssl` após a linha 19:

ssl: {
        rejectUnauthorized: false,
      },

**Comment by thiagocleite** [comment]
@tiagos4ntos
Feito!
